### ISSUE TITLE
Plugin not working with latest version of PyCharm 2021.1

### ISSUE THREAD

**Issue by jlconnor** [julienr/pycharm-cellmode#16]
com.intellij.diagnostic.PluginException: Cannot create class PythonCellLineSeparatorProvider (classloader=PluginClassLoader(plugin=PluginDescriptor(name=PyCharm cell mode, id=net.fhtagn.pycharm.cellmode, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.6693.115/PyCharm.app.plugins/PythonCellMode.jar, version=1.2.1, package=null), packagePrefix=null, instanceId=79, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:763)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:781)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:54)
	at com.intellij.serviceContainer.LazyExtensionInstance.getInstance(LazyExtensionInstance.java:43)
	at com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance(BaseKeyedLazyInstance.java:38)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensionsFromExtensionPoint(KeyedExtensionCollector.java:155)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:128)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:147)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:16)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:109)
	at com.intellij.lang.LanguageExtension.collectAllForLanguage(LanguageExtension.java:125)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:116)
	at com.intellij.lang.LanguageExtension.allForLanguageOrAny(LanguageExtension.java:160)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.getMarkerProviders(LineMarkersPass.java:134)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:79)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoSuchMethodException: PythonCellLineSeparatorProvider.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:720)
	... 34 more

**Comment by ss005** [comment]
Hi @jlconnor , I'm also facing this error, I've tried to fix it and raised a PR here:

https://github.com/julienr/pycharm-cellmode/pull/17

Meanwhile you can try the attached plugin, and see if it works for you. Also it will re-verify that changes in PR are working.

[PythonCellMode.zip](https://github.com/julienr/pycharm-cellmode/files/6281262/PythonCellMode.zip)

Thanks!

**Comment by afargnoli-ops** [comment]
How would I install a plugin from a zip file? I'm a novice when it comes to IntelliJ.

**Comment by ss005** [comment]
@afargnoli-ops 

- Uninstall this plugin if you have previously installed and restart Pycharm/Intellij
- extract jar file from zip.
- go to File -> Settings -> Plugins -> Gear icon -> Install Plugin from Disk -> select the jar file -> Restart Pycharm/Intellij.

<img width="649" alt="plugin" src="https://user-images.githubusercontent.com/8335298/114660722-6aff7c80-9d13-11eb-9ba2-9b3fc36aaca4.png">

**Comment by afargnoli-ops** [comment]
@ss005 , thanks! I will give that a try.

**Comment by julienr** [comment]
Thanks for reporting and proposing a fix for this. I'll try to get to
review the PR and update the plugin this weekend.

In the meantime, if you can confirm the fix that's awesome !

**Comment by joshburnett** [comment]
I downloaded the file provided by @ss005 and it works for me in 2021.1. Thanks!

**Comment by afargnoli-ops** [comment]
It works for me too in 2021.1. Thanks!

**Comment by dkfurrow** [comment]
Also tested, works fine for me in 2021.1.1, Build #PY-211.7142.13.  Thanks @ss005!

**Comment by ski123786** [comment]
The PythonCellMode.zip file works like a charm. Thanks!

**Comment by julienr** [comment]
I've pushed a new build that is compatible with 2021.1 to the jetbrains plugin repository. There might be a bit of delay, but in the meantime you can install from [this jar](https://github.com/julienr/pycharm-cellmode/blob/master/PythonCellMode.jar).

Thanks for helping fix this issue !
